apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: book-system-updater
  namespace: argocd
spec:
  namespace: argocd
  applicationRefs:
    - namePattern: "book-system"
      images:
        - alias: "book-system"
          imageName: "registry.uniproject.jp/nnn/book-system:x.x.x-x"
          commonUpdateSettings:
            updateStrategy: "semver"
