name: book-system
services:
  db:
    image: mariadb:lts
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: booksystem
      MARIADB_USER: bookuser
      MARIADB_PASSWORD: bookpassword
      TZ: "Asia/Tokyo"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db_data:
