import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { Student } from "@/class/Student";
import AppThemeProvider from "@/components/AppThemeProvider";
import StudentInitializeGuard from "@/components/StudentInitializeGuard";
import Sidebar from "@/components/sidebar";
import { auth } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  if (!session?.user) {
    redirect("/signin");
  }

  const student = await Student.findBySession();
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppThemeProvider>
          <StudentInitializeGuard uid={session.user.id} open={!student} />
          <Sidebar user={session.user}>{children}</Sidebar>
        </AppThemeProvider>
      </body>
    </html>
  );
}
