import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { headers } from "next/headers";
import CampusInitialize from "@/components/CampusInitializeGuard";
import Sidebar from "@/components/sidebarAdmin";
import { auth } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { redirect } from "next/navigation";
import AppThemeProvider from "@/components/AppThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });
  if (!session) {
    redirect("/signin");
  }
  const campus = await prisma.campus.findFirst(); // キャンパス情報が存在するか確認
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppThemeProvider isAdmin>
          <Sidebar user={session.user}>{children}</Sidebar>
          <CampusInitialize open={!campus} />
        </AppThemeProvider>
      </body>
    </html>
  );
}
