DROP TABLE IF EXISTS `campus`;
CREATE TABLE IF NOT EXISTS `campus_config` (
  `key` VARCHAR(255) NOT NULL PRIMARY KEY,
  `value` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;